/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alvar
 */
public class FrmVentana extends javax.swing.JFrame {

    /**
     * Creates new form FrmVentana
     */
    Paquete q;

    public FrmVentana(Paquete w) {
        initComponents();
        q = w;
        System.out.println(q);
        cbPaquetes.removeAllItems();
        cbPaquetes.addItem("Seleccione una opcion");

        cbPaquetes.addItem(q.getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbPaquetes = new javax.swing.JComboBox();
        cbClases = new javax.swing.JComboBox();
        cbAtributos = new javax.swing.JComboBox();
        cbMetodos = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Archivo:");

        jLabel2.setText("Clases:");

        jLabel3.setText("Atributos:");

        jLabel4.setText("Metodos:");

        cbPaquetes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPaquetes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPaquetesItemStateChanged(evt);
            }
        });

        cbClases.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbClases.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbClasesItemStateChanged(evt);
            }
        });

        cbAtributos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAtributos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAtributosItemStateChanged(evt);
            }
        });

        cbMetodos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbPaquetes, 0, 124, Short.MAX_VALUE)
                    .addComponent(cbClases, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbAtributos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbMetodos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbPaquetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPaquetesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPaquetesItemStateChanged
        // TODO add your handling code here:
        cbClases.removeAllItems();
        cbClases.addItem("Seleccione una opcion");

        int combo = cbPaquetes.getSelectedIndex();
        if (combo != -1) {
            for (int i = 0; i < q.getListaClase().size(); i++) {
                if (cbPaquetes.getSelectedItem().equals(q.getNombre())) {
                    cbClases.addItem(q.getListaClase().get(i).getNombreClase());
                }
            }
        }
    }//GEN-LAST:event_cbPaquetesItemStateChanged

    private void cbAtributosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAtributosItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cbAtributosItemStateChanged

    private void cbClasesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbClasesItemStateChanged
        // TODO add your handling code here:
        cbAtributos.removeAllItems();
        cbAtributos.addItem("Seleccione una opcion");

        cbMetodos.removeAllItems();
        cbMetodos.addItem("Seleccione una opcion");

        int combo = cbClases.getSelectedIndex();
        if (combo != -1) {
            for (int i = 0; i < q.getListaClase().size(); i++) {
                if (cbClases.getSelectedItem().equals(q.getListaClase().get(i).getNombreClase())) {
                    for (int j = 0; j < q.getListaClase().get(i).getAtributos().size(); j++) {
                        cbAtributos.addItem(q.getListaClase().get(i).getAtributos().get(j));
                    }
                    for (int j = 0; j < q.getListaClase().get(i).getMetodos().size(); j++) {
                        cbMetodos.addItem(q.getListaClase().get(i).getMetodos().get(j));
                    }
                }
            }
        }
    }//GEN-LAST:event_cbClasesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbAtributos;
    private javax.swing.JComboBox cbClases;
    private javax.swing.JComboBox cbMetodos;
    private javax.swing.JComboBox cbPaquetes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
